export { default as Content } from './Content/Content';
export { default as Footer } from './Footer/Footer';
export { default as IndividualLink } from './IndividualLink/IndividualLink';
export { default as Intro } from './Intro/Intro';
export { default as LinkListPage } from './LinkListPage/LinkListPage';
export { default as Login } from './Login/Login';
// export { default as NavBar } from './NavBar/NavBar';
export { default as NewNavBar } from './NewNavBar/NewNavBar';
export { default as NoMatch } from './NoMatch/NoMatch';
export { default as Register } from './Register/Register';
// export { default as SideBar } from './SideBar/SideBar';
export { default as Menu } from './Menu/Menu';
export { default as SubmitLink } from './SubmitLink/SubmitLink';
